Data:
  batch_size: 256
  max_num_ptcs: 16
  min_num_ptcs: 4
  num_test: 50
  num_train: 250
  num_valid: 50
  pt_threshold: 0.025
JetNet:
  dataset: JetNet
  num_classes: 5
  pt_max: 1200
  pt_min: 800
Performance:
  benchmark_mode: true
  cpu_worker_fraction: 0.8
  gpu_memory_fraction: 0.8
  num_workers: 8
  pin_memory: true
  use_mixed_precision: true
Settings:
  mode: '111'
  print_log: true
  suffix: ''
  use_wandb: false
TopQCD:
  dataset: TopQCD
  num_classes: 2
  pt_max: 650
  pt_min: 550
Train:
  ckpt_mode: max
  ckpt_monitor: valid_auc
  ckpt_top_k: 5
  log_every_n_steps: 50
  max_epochs: 1
  num_sanity_val_steps: 0
cpu: Unknown_CPU
data_description: JetNet_P16_N250
dataset: JetNet
date: '20251109_210223'
edge_conv:
- - 3
  - - - 64
      - 64
    - - 64
      - 64
    - - 64
      - 64
- - 3
  - - - 64
      - 128
    - - 128
      - 128
    - - 128
      - 128
fc:
- - 0.1
  - - 128
    - 256
- - 0.1
  - - 256
    - 256
gpu: NVIDIA_GeForce_RTX_3080
group_rnd: ParticleNet--JetNet_P16_N250
input_dim: 3
lr: 0.001
model: ParticleNet
model_description: ''
name: ParticleNet--JetNet_P16_N250-42
num_cpu_cores: 24
num_threads: 12
random_seed: 42
